package com.hope.master_service.dto.response;

public enum ResponseCode {
    // HTTP Status Codes
    INTERNAL_ERROR,
    ACCESS_DENIED,
    BAD_REQUEST,
    NOT_FOUND,
    CREATED,
    UNSUPPORTED_MEDIA_TYPE,
    OK,
    UNAUTHORIZED,

    // Application Status Code
    SERVICE_UNAVAILABLE,
    ENTITY,
    DB_ERROR,
    IAM_ERROR,
    AWS_ERROR,
    USER_ARCHIVED,
    USER_UNARCHIVED,
    USER_NOT_EXIST,
    BILLING_INVOICE_STATEMENT,

    // Login
    INVALID_CREDENTIALS,
    LOGIN_FAILED,
    INVALID_REFRESH_TOKEN,

    // Logout
    LOGOUT_RESPONSE,
    LOGOUT_FAILED,

    // Password
    SET_PASSWORD_RESPONSE,
    INVALID_PASSWORD_LINK,
    INVALID_PASSWORD,
    RESET_PASSWORD_FAILED,
    CHANGE_PASSWORD_RESPONSE,
    VERIFY_PASSWORD_LINK_RESPONSE,
    FORGOT_PASSWORD_RESPONSE,
    RESEND_INVITE_EMAIL_RESPONSE,
    PASSWORDS_DO_NOT_MATCH,

    // OTP
    OTP_SENT,
    OTP_VERIFIED,
    OTP_INVALID,
    OTP_EXPIRED,
    OTP_MAX_ATTEMPTS,
    OTP_RESET_TOKEN_INVALID,

    // User
    USER_CREATED,
    USER_NOT_FOUND,
    USER_EMAIL_NOT_FOUND,
    UPDATE_USER_PROFILE_RESPONSE,
    USER_ENABLED,
    USER_DISABLED,
    DUPLICATE_EMAIL_ERROR,
    CHANGE_AVATAR_RESPONSE,
    USER_EMAIL_REQUIRED,
    USER_EMAIL_UPDATE_ERROR,
    INVALID_USER_ROLE,
    USER_EMAIL_VERIFIED,
    SIGNED_UP,
    USER_INACTIVE,
    EMPTY_EMAIL,
    MAIL_SENT_SUCCESSFULLY,

    // Provider Group
    PROVIDER_GROUP_CREATED,
    PROVIDER_GROUP_UPDATED,
    FAILED_UPDATE_PROVIDER_GROUP,
    PROVIDER_GROUP_ENABLED,
    PROVIDER_GROUP_DISABLED,
    PROVIDER_GROUP_ARCHIVED,
    PROVIDER_GROUP_UNARCHIVED,


    //Locations
    LOCATION_CREATED,
    LOCATION_UPDATED,
    LOCATION_NOT_FOUND,
    LOCATION_ENABLED,
    LOCATION_DISABLED,
    LOCATION_ARCHIVED,
    LOCATION_UNARCHIVED,

    //DEPARTMENT
    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DEPARTMENT_ENABLED,
    DEPARTMENT_DISABLED,
    DEPARTMENT_ARCHIVED,
    DEPARTMENT_UNARCHIVED,

    // Organization
    ORGANIZATION_CREATED,
    ORGANIZATION_UPDATED,
    ORGANIZATION_NOT_FOUND,
    ORGANIZATION_ARCHIVED,
    ORGANIZATION_UNARCHIVED,
    ORGANIZATION_NAME_ALREADY_EXISTS,
    ORGANIZATION_ACTIVATED,
    ORGANIZATION_DEACTIVATED,

    // Sub-Organization
    SUB_ORGANIZATION_CREATED,
    SUB_ORGANIZATION_UPDATED,
    SUB_ORGANIZATION_NOT_FOUND,
    SUB_ORGANIZATION_ACTIVATED,
    SUB_ORGANIZATION_DEACTIVATED,
    SUB_ORGANIZATION_ARCHIVED,
    SUB_ORGANIZATION_UNARCHIVED,
    SUB_ORGANIZATION_NAME_ALREADY_EXISTS,

    // Referrer
    REFERRER_CREATED,
    REFERRER_UPDATED,
    REFERRER_NOT_FOUND,
    REFERRER_ARCHIVED,
    REFERRER_UNARCHIVED,

    // Provider
    PROVIDER_CREATED,
    PROVIDER_UPDATED,
    PROVIDER_ENABLED,
    PROVIDER_DISABLED,
    PROVIDER_ARCHIVED,
    PROVIDER_UNARCHIVED,
    NPI_ALREADY_EXIST,

    // Patient
    PATIENT_CREATED,
    PATIENT_UPDATE,
    PATIENT_STATUS_UPDATED,
    PATIENT_ARCHIVE_STATUS_UPDATED,
    PATIENT_UNARCHIVE_STATUS_UPDATED,
    PATIENT_ENABLE_DISABLE_RESPONSE,
    FAILED_PATIENT_UPDATE,
    PATIENT_NOT_FOUND,
    USER_MRN_UPDATE_ERROR,
    PATIENT_DATA_FETCHED,
    PATIENT_DOCUMENT_REMOVED,
    UPLOAD_DOC_INVALID_ERROR,
    FAILED_PATIENT_STATUS_UPDATE,
    PATIENT_ARCHIVE,
    FAILED_PATIENT_ARCHIVE,
    INVALID_BIRTHDATE,
    FAILED_UPDATE_PATIENT_INSURANCE,
    ADDED_TO_WAITING_LIST,

    // Tenant Configuration
    TENANT_CONFIGURATION_CREATED,
    TENANT_CONFIGURATION_UPDATED,

//    todo: below this need to be refactored.

    // Fee Amount
    FEE_AMOUNT_ADDED, FEE_AMOUNT_UPDATED, FEE_AMOUNT_STATUS_CHANGED, FEE_AMOUNT_ALREADY_EXISTS, FEE_AMOUNT_NOT_FOUND, FEE_DELETED,

    // Medical Code
    INVALID_MEDICAL_CODE,
    // Patient
    PATIENT_ADDED,
    PATIENT_ARCHIVED,
    PATIENT_UNARCHIVED,
    PATIENT_ENABLED,
    PATIENT_DISABLED,


    //Insurance
    INSURANCEPAYER_NOT_FOUND, INSURANCE_POLICY_NOT_FOUND, TOO_MANY_INSURANCES, INSURANCE_NOT_FOUND, SECONDARY_INSURANCE_NOT_FOUND, INSURANCETYPE_UPDATED, CANNOT_UPDATE_INSURANCETYPE, PATIENT_INSURANCE_UPDATE, PATIENT_INSURANCE_FETCHED, SECONDARY_INSURANCE_REMOVED, DUPLICATE_INSURANCE_ERROR,
    ELIGIBILITY_NOT_ALLOWED, PATIENT_INSURANCE_CREATED, CLAIM_INSURANCE_REQUIRED,

    //Intake form
    INTAKE_FORM_ADDED, INTAKE_FORM_UPDATED, PATIENT_DOCUMENT_UPLOADED, REASON_IS_MANDATORY, CHARGEABLE_IS_MANDATORY, INTAKE_NEEDED,

    //Consent form template
    CONSENT_FORM_FOUND,

    // Availability
    ADDED_AVAILABILITY, CONSULT_TIME_CONFLICT, BOOKED_APPOINTMENT_SLOT, AVAILABILITY_NOT_FOUND, DAY_SLOT_NOT_FOUND, SLOT_NOT_FOUND,
    INVALID_TIME_DURATION, PAST_START_TIME,

    // Appointment
    SLOT_ALREADY_BOOKED, APPOINTMENT_CREATED, APPOINTMENT_DATA_FETCHED, APPOINTMENT_NOT_FOUND, APPOINTMENT_UPDATED, APPOINTMENT_CONFIRMED,
    NEW_APPT_ALREADY_EXIST, NEW_APPT_NOT_EXIST, EXISTING_APPOINTMENT_NOT_FOUND, RESCHEDULE_NOT_ALLOWED, APPOINTMENT_RESCHEDULED, APPOINTMENT_RESCHEDULED_WITH_CHARGE, CHECKED_IN_NOT_ENABLED, FOLLOW_UP_APPT_ERROR, APPT_NOT_COMPLETE_ERROR, EXISTING_APPT_STATUS_ERROR,
    APPOINTMENT_FEE_SET, APPOINTMENT_FEE_ALREADY_PAID, NO_SHOW_NOT_ALLOWED, BILL_AMOUNT,

    // Communication
    SEND_MESSAGE_RESPONSE, EMAIL_SUBJECT_MANDATORY, PATIENT_PHONE_NOT_PRESENT,

    //Encounter
    ENCOUNTER_CREATED, ENCOUNTER_ALREADY_EXIST, ENCOUNTER_ARCHIVED, ENCOUNTER_UPDATED, ENCOUNTER_FETCHED, ENCOUNTER_NOT_FOUND,

    // Patient- Screener
    PATIENT_SCREENER_ADDED, PATIENTSCREENER_NOT_FOUND, PATIENT_SCORE_ADDED, PATIENT_SCREENER_ANSWER_UPDATED, INVALID_SCREENER_TYPE, INVALID_ANSWER_OPTION, INCOMPLETE_SCREENER_ANSWERS, PATIENT_SCREENER_SCORE_UPDATED, PATIENT_SCREENER_DATA_FETCHED,

    // PAYMENT
    PAYMENT_CARD_ADDED, PAYMENT_CARD_ALREADY_EXISTS, PAYMENT_CHARGED, FINE_CHARGED, PAYMENT_CARD_NOT_FOUND, PAYMENT_ALREADY_DONE, PAYMENT_CARD_NOT_EXISTS, PAYMENT_AMOUNT_NOT_SET, PAYMENT_BILL_STATUS_ERROR,
    INVALID_CARD_EXPIRATION,

    //Notification
    NO_NOTIFICATIONS, NOTIFICATION_MARKED_AS_SEEN, NOTIFICATIONS_COUNT,

    //Patients consent form
    PATIENT_CONSENT_FORMS_ADDED,

    //Text macros
    TEXTMACRO_SHORTCUT_EXISTS, TEXTMACRO_ADDED, TEXTMACRO_DATA_FETCHED, TEXTMACRO_UPDATED, FAILED_UPDATE_TEXT_MACRO, FAILED_TEXTMACRO_ARCHIVE, TEXTMACRO_ARCHIVE,
    TEXTMACRO_RESTORED, FAILED_TEXTMACRO_RESTORE, TEXTMACRO_NOT_EXIST,

    //Task
    TASK_ADDED,
    TASK_DATA_FETCHED,
    TASK_UPDATED,
    TasK_ENABLED,
    TasK_DISABLED,
    TasK_ARCHIVED,
    TasK_UNARCHIVED,
    TASK_ASSIGNED,
    INVALID_TASK_STATUS,
    INVALID_DUEDATE, FINE_CHARGED_APPOINTMENT, APPOINTMENT_FINE, CANNOT_CHARGE_FINE, PAYMENT_SUCCESSFUL,

    //Patient_Vital
    VITAL_ADDED, VITAL_UPDATED, VITAL_DATA_FETCHED, VITAL_NOT_FOUND, FAILED_VITAL_UPDATED,


    //Video notification
    EMITTED_SUCCESSFULLY,

    //Scriptsure webhookVITAL_DATA_FETCHED
    WEBHOOK_SUCCESSFUL,

    //BILL
    BILL_UPDATED,

    //CLAIM
    CLAIM_ADDED,


    //Zocdoc
    BOOK_APPOINTMENT_ERROR, CANCEL_APPOINTMENT_ERROR, NOT_IMPLEMENTED,

    //Patient comment
    COMMENT_ADDED_SUCCESSFULLY,
    COMMENT_UPDATED_SUCCESSFULLY,
    COMMENT_DELETED_SUCCESSFULLY,

    //medical code
    MEDICAL_CODE_ADDED_SUCCESSFULLY,
    MEDICAL_CODE_UPDATED_SUCCESSFULLY,

    //Provider review
    PROVIDER_REVIEW_ADDED_SUCCESSFULLY,
    PROVIDER_REVIEW_STATUS_UPDATED_SUCCESSFULLY,
    CHECK_IN_STATUS,

    //Patient order
    REFILL_RX_ADDED,
    REFILL_RX_UPDATED,

    //Release of information
    ROI_ADDED, ROI_UPDATED, ROI_STATUS_UPDATED, ROI_NOT_FOUND,

    CONSENT_FORM_TEMPLATE_ADDED, CONSENT_FORM_TEMPLATE_UPDATED, CONSENT_FORM_TEMPLATE_STATUS,
    INTERNAL_SERVER_ERROR, FILE_UPLOADED, EMPTY_FILE,

    //Medical Codes
    MEDICAL_CODES_CREATED,
    MEDICAL_CODES_UPDATED,
    MEDICAL_CODE_ENABLED,
    MEDICAL_CODE_DISABLED,

    MEDICAL_CODE_ARCHIVED,
    MEDICAL_CODE_UNARCHIVED,

    //Patient Diagnosis
    PATIENT_DIAGNOSIS_CREATED,
    PATIENT_DIAGNOSIS_UPDATED,
    PATIENT_DIAGNOSIS_ENABLED,
    PATIENT_DIAGNOSIS_DISABLED,
    PATIENT_DIAGNOSIS_ARCHIVED,
    PATIENT_DIAGNOSIS_UNARCHIVED,

    //Patient Allergy
    PATIENT_ALLERGY_CREATED,
    PATIENT_ALLERGY_UPDATED,
    PATIENT_ALLERGY_ENABLED,
    PATIENT_ALLERGY_DISABLED,
    PATIENT_ALLERGY_ARCHIVED,
    PATIENT_ALLERGY_UNARCHIVED,

    //Patient Vaccine
    PATIENT_VACCINE_CREATED,
    PATIENT_VACCINE_UPDATED,
    PATIENT_VACCINE_ENABLED,
    PATIENT_VACCINE_DISABLED,
    PATIENT_VACCINE_ARCHIVED,
    PATIENT_VACCINE_UNARCHIVED,

    //Patient Vital
    PATIENT_VITAL_CREATED,
    PATIENT_VITAL_UPDATED,

    //Sticky Notes
    STICKY_NOTE_CREATED,
    STICKY_NOTE_UPDATED,
    STICKY_NOTE_ENABLED,
    STICKY_NOTE_DISABLED,
    STICKY_NOTE_ARCHIVED,
    STICKY_NOTE_UNARCHIVED,


    // PATIENT MEDICATION
    PATIENT_MEDICATION_CREATED, PATIENT_MEDICATION_UPDATED, PATIENT_MEDICATION_ENABLED, PATIENT_MEDICATION_DISABLED, PATIENT_MEDICATION_ARCHIVED, PATIENT_MEDICATION_UNARCHIVED,

    // PATIENT MEDICAL HISTORY
    PATIENT_MEDICAL_HISTORY_CREATED, PATIENT_MEDICAL_HISTORY_UPDATED, PATIENT_MEDICAL_HISTORY_ENABLED, PATIENT_MEDICAL_HISTORY_DISABLED, PATIENT_MEDICAL_HISTORY_ARCHIVED, PATIENT_MEDICAL_HISTORY_UNARCHIVED,

    // PATIENT SURGICAL HISTORY
    PATIENT_SURGICAL_HISTORY_CREATED, PATIENT_SURGICAL_HISTORY_UPDATED, PATIENT_SURGICAL_HISTORY_ENABLED, PATIENT_SURGICAL_HISTORY_DISABLED, PATIENT_SURGICAL_HISTORY_ARCHIVED, PATIENT_SURGICAL_HISTORY_UNARCHIVED,

    // PATIENT FAMILY HISTORY
    PATIENT_FAMILY_HISTORY_CREATED, PATIENT_FAMILY_HISTORY_UPDATED, PATIENT_FAMILY_HISTORY_ENABLED, PATIENT_FAMILY_HISTORY_DISABLED, PATIENT_FAMILY_HISTORY_ARCHIVED, PATIENT_FAMILY_HISTORY_UNARCHIVED,

    // PATIENT SOCIAL HISTORY
    PATIENT_SOCIAL_HISTORY_CREATED, PATIENT_SOCIAL_HISTORY_UPDATED, PATIENT_SOCIAL_HISTORY_ENABLED, PATIENT_SOCIAL_HISTORY_DISABLED, PATIENT_SOCIAL_HISTORY_ARCHIVED, PATIENT_SOCIAL_HISTORY_UNARCHIVED,

    // Document Tag
    DOCUMENT_TAG_CREATED,
    DOCUMENT_TAG_UPDATED,
    DOCUMENT_TAG_ENABLED,
    DOCUMENT_TAG_DISABLED,
    DOCUMENT_TAG_ARCHIVED,
    DOCUMENT_TAG_UNARCHIVED,

    // Patient Lab Order
    PATIENT_LAB_ORDER_CREATED,
    PATIENT_LAB_ORDER_UPDATED,
    PATIENT_LAB_ORDER_NOT_FOUND,
    PATIENT_LAB_ORDER_ENABLED,
    PATIENT_LAB_ORDER_DISABLED,
    PATIENT_LAB_ORDER_ARCHIVED,
    PATIENT_LAB_ORDER_UNARCHIVED,


    // Clinical Note
    CLINICAL_NOTE_CREATED,
    CLINICAL_NOTE_UPDATED,
    CLINICAL_NOTE_NOT_FOUND,
    CLINICAL_NOTE_ENABLED,
    CLINICAL_NOTE_DISABLED,
    CLINICAL_NOTE_ARCHIVED,
    CLINICAL_NOTE_UNARCHIVED,


    //User Document upload
    USER_DOCUMENT_UPLOAD,

    //RolesAndPrivileges
    ROLE_ADDED, PRIVILEGE_NOT_FOUND, ROLE_UPDATED, ROLE_NOT_FOUND,

    // Custom Form
    CUSTOM_FORM_CREATED, CUSTOM_FORM_STATUS_UPDATED, CUSTOM_FORM_UPDATED, CUSTOM_FORM_ENABLED, CUSTOM_FORM_DISABLED, CUSTOM_FORM_ARCHIVED, CUSTOM_FORM_UNARCHIVED, CUSTOM_FORM_RESTORED, CUSTOM_FORM_COPY,

    // Custom Form Template
    CUSTOM_FORM_TEMPLATE_CREATED, CUSTOM_FORM_TEMPLATE_STATUS_UPDATED, CUSTOM_FORM_TEMPLATE_UPDATED, CUSTOM_FORM_TEMPLATE_ENABLED, CUSTOM_FORM_TEMPLATE_DISABLED, CUSTOM_FORM_TEMPLATE_ARCHIVED, CUSTOM_FORM_TEMPLATE_RESTORED,

    // Micros Form
    MICROS_FORM_CREATED, MICROS_FORM_UPDATED, MICROS_FORM_STATUS_UPDATED, MICROS_FORM_ARCHIVE_STATUS_UPDATED,

    // Visit Note Form
    VISIT_NOTE_FORM_CREATED, VISIT_NOTE_FORM_UPDATED, VISIT_NOTE_FORM_STATUS_UPDATED, VISIT_NOTE_FORM_ARCHIVE_STATUS_UPDATED,

    // Review Of System Form
    REVIEW_OF_SYSTEM_FORM_CREATED, REVIEW_OF_SYSTEM_FORM_UPDATED, REVIEW_OF_SYSTEM_FORM_STATUS_UPDATED, REVIEW_OF_SYSTEM_FORM_ARCHIVE_STATUS_UPDATED,

    // Custom Questionnaire Form
    CUSTOM_QUESTIONNAIRE_FORM_CREATED, CUSTOM_QUESTIONNAIRE_FORM_UPDATED, CUSTOM_QUESTIONNAIRE_FORM_STATUS_UPDATED, CUSTOM_QUESTIONNAIRE_FORM_ARCHIVE_STATUS_UPDATED,

    // CarePlan Form
    CAREPLAN_FORM_CREATED, CAREPLAN_FORM_UPDATED, CAREPLAN_FORM_STATUS_UPDATED, CAREPLAN_FORM_ARCHIVE_STATUS_UPDATED,

    // Annotable Image Form
    ANNOTABLE_IMAGE_FORM_CREATED, ANNOTABLE_IMAGE_FORM_UPDATED, ANNOTABLE_IMAGE_FORM_STATUS_UPDATED, ANNOTABLE_IMAGE_FORM_ARCHIVE_STATUS_UPDATED,

    // Order Set Form
    ORDER_SET_FORM_CREATED, ORDER_SET_FORM_UPDATED, ORDER_SET_FORM_STATUS_UPDATED, ORDER_SET_FORM_ARCHIVE_STATUS_UPDATED,

    // Physical Exam Form
    PHYSICAL_EXAM_FORM_CREATED, PHYSICAL_EXAM_FORM_UPDATED, PHYSICAL_EXAM_FORM_STATUS_UPDATED, PHYSICAL_EXAM_FORM_ARCHIVE_STATUS_UPDATED,

    //  todo:  below variables arerelated to availability need to check
    CHECK_CONSULT_TIME,

    ICD_CODE_ADDED,
    CPT_CODE_ADDED,
    HCPCS_CODE_ADDED,
    LOINC_CODE_ADDED,

    ICD_CODE_UPDATED,
    CPT_CODE_UPDATED,
    HCPCS_CODE_UPDATED,
    LOINC_CODE_UPDATED,

    // fee schedule
    FEE_SCHEDULE_ADDED,
    FEE_SCHEDULE_UPDATED,
    FEE_SCHEDULE_ARCHIVED,
    FEE_SCHEDULE_UNARCHIVED,
    FEE_SCHEDULE_NOT_FOUND,
    FEE_SCHEDULE_FETCHED,

    // Super Bill
    SUPER_BILL_CREATED,
    SUPER_BILL_UPDATED,
    SUPER_BILL_ARCHIVED,
    SUPER_BILL_UNARCHIVED,
    SUPER_BILL_NOT_FOUND,
    SUPER_BILL_PAYMENT_ADDED,
    SUPER_BILL_PAYMENT_FETCHED,
    SUPER_BILL_FETCHED,
    SUPER_BILL_DISCARDED,
    SUPER_BILL_INVALID_AMOUNT,

    // Claim
    CLAIM_CREATED,
    CLAIM_NOT_FOUND,
    CLAIM_FETCHED,
    CLAIM_UPDATED,
    CLAIM_ARCHIVED,
    CLAIM_UNARCHIVED,
    CLAIM_STATUS_UPDATED,

    // place of services
    PLACE_OF_SERVICES,

    // edi batches
    EDI_BATCH_CREATED,
    EDI_BATCH_UPDATED,
    EDI_BATCH_ARCHIVED,
    EDI_BATCH_UNARCHIVED,
    EDI_BATCH_NOT_FOUND,
    EDI_BATCH_FETCHED,
    EDI_BATCH_STATUS_UPDATED, TRANSACTION_FETCHED, EDI_BATCH_PROCESSING, NO_CONTENT, EDI_271_UPLOADED,

    // Patient payments
    PATIENT_PAYMENT_ADDED,
    PATIENT_PAYMENT_UPDATED,
    PATIENT_PAYMENT_NOT_FOUND,
    PATIENT_PAYMENT_FETCHED,
    PATIENT_PAYMENT_ARCHIVED, PATIENT_PAYMENT_APPLIED, PATIENT_PAYMENT_APPLIED_FETCHED, SERVICE_TYPE_CODES,

    // Prior Authorization
    PRIOR_AUTHORIZATION_CREATED,
    PRIOR_AUTHORIZATION_UPDATED,
    PRIOR_AUTHORIZATION_NOT_FOUND,
    PRIOR_AUTHORIZATION_FETCHED,
    PRIOR_AUTHORIZATION_ARCHIVED,
    PRIOR_AUTHORIZATION_UNARCHIVED,
    PRIOR_AUTHORIZATION_STATUS_UPDATED,
    PRIOR_AUTHORIZATION_DELETED,

    // File Upload Validation
    CSV_INVALID_HEADERS,
    CSV_MISSING_REQUIRED_COLUMN,
    CSV_MISSING_REQUIRED_FIELD,
    CSV_INVALID_DATA_FORMAT,
    CSV_DUPLICATE_RECORDS_FOUND,
    CSV_ALL_RECORDS_INVALID,
    CSV_PARTIAL_SUCCESS_WITH_ERRORS,
    CSV_VALIDATION_FAILED,
    CODE_FIELD_REQUIRED,
    DESCRIPTION_FIELD_REQUIRED,
    DUPLICATE_CODE_SKIPPED,
    DUPLICATE_PROVIDER_NPI_SKIPPED,

    // Contract
    CONTRACT_CREATED,
    CONTRACT_UPDATED,
    CONTRACT_NOT_FOUND,
    CONTRACT_ARCHIVED,
    CONTRACT_UNARCHIVED,
    CONTRACT_NAME_ALREADY_EXISTS,
    CONTRACT_IDENTIFIER_ALREADY_EXISTS,
    CONTRACT_ACTIVATED,
    CONTRACT_DEACTIVATED,
    CONTRACT_SUSPENDED,
    CONTRACT_CLONED,
    CONTRACT_MAX_TERMS_EXCEEDED,
    CONTRACT_TERM_INVALID_DATES,
    CONTRACT_TERM_OVERLAP,
    CONTRACT_SUB_ORG_ALREADY_ASSIGNED,

    // Homework
    HOMEWORK_CREATED,
    HOMEWORK_UPDATED,
    HOMEWORK_NOT_FOUND,
    HOMEWORK_ARCHIVED,
    HOMEWORK_UNARCHIVED,
    HOMEWORK_DELETED,
    HOMEWORK_NAME_ALREADY_EXISTS,
    HOMEWORK_IN_USE,
    HOMEWORK_DOCUMENT_REPLACED,
    HOMEWORK_DOCUMENT_REMOVED,
    HOMEWORK_DOCUMENT_NOT_FOUND,
    HOMEWORK_INVALID_FILE_TYPE,
    HOMEWORK_CURRICULUM_UPDATED,
    HOMEWORK_CURRICULUM_NOT_FOUND,
    HOMEWORK_ALREADY_IN_CURRICULUM;


    private ResponseCode() {
    }
}